### ISSUE TITLE
Set webserver roles to clone pull the geoserver/data repository

### ISSUE THREAD

**Issue by giacomoc92** [geosolutions-it/C106-2017#10]
The roles should also include a task to reload the webserver.

I.E. `curl -u 'username:password' -XPOST 'localhost:8080/geoserver/rest/reload'`

**Comment by randomorder** [comment]
https://github.com/geosolutions-it/C106-2017/commit/e60e8148157596d658a26d92045366a60300ea69

**Comment by randomorder** [comment]
![config_update](https://user-images.githubusercontent.com/5264230/69430562-3235c080-0d36-11ea-9518-0b34da31154f.gif)
