### ISSUE TITLE
Externalizations and java opts

### ISSUE THREAD

**Issue by giacomoc92** [geosolutions-it/C106-2017#11]

**Comment by giacomoc92** [comment]
@randomorder what needs to be externalize? what java opts needs to be set?

**Comment by randomorder** [comment]
Directories:
- geoserver logs
 - audits directory
- geoserver datadir
- gwc config dir
- gwc cache dir

This is done via Java Opts:

Provisional Java Opts (we'll improve them later):
```
JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOSERVER_DATA_DIR=/path/to/datadir -DGEOWEBCACHE_CONFIG_DIR=/path/to/datadir/gwc -DGEOSERVER_LOG_LOCATION=/path/to/logs/dir/geoserver.log -DGEOSERVER_NODE_OPTS=id:<color> -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/path/to//webapps/dir/geoserver/WEB-INF/lib/marlin-0.9.2-Unsafe.jar -Xbootclasspath/p:/path/to//webapps/dir/geoserver/WEB-INF/lib/marlin-0.9.2.sun-java2d.jar -DGEOSERVER_AUDIT_PATH=/path/to/audits/dir/ -DPROXY_BASE_URL=http://publichostname/geoserver
```
Note: 
- "-Xms1024m -Xmx1024m" those numbers Must be configurable in Ansible
- make sure these files exist: /path/to//webapps/dir/geoserver/WEB-INF/lib/marlin-0.9.2-Unsafe.jar /path/to//webapps/dir/geoserver/WEB-INF/lib/marlin-0.9.2.sun-java2d.jar
- <color> we assign a different color to each one of the geoserver instances "red" and "blue"
- place all externalized directories under /var where the CATALINA_BASE of the Tomcat installation for GeoServer is

**Comment by giacomoc92** [comment]
A basic cofiguration for this issue has already been merged in the main repo. 

Todo:

- complete configuration
- testing

**Comment by randomorder** [comment]
TODO: test audits externalization when we have monitor plugin installed and configured
