### ISSUE TITLE
haproxy configuration

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/C106-2017#24]
review and test haproxy conf
- [x] balancing algorithm as per client request:  `least con algorithm`
- [ ] test what happens when geoservers go up and down
- [ ] test what happens on configuration updates

**Comment by giacomoc92** [comment]
I have set the loadbalancer to leastconn and tested it with geoservers up and downs, everything is working correctly, the lb only redirects connections to the working geoserver.

There where problems with tomcat not starting after a server restart, switching to a faster server seems to have solved those, although it is still taking a really long time to start. 

> test what happens on configuration updates
Lb keeps working by disabling either gs2 or gs1 as backends

**Comment by randomorder** [comment]
ok, thanks
That is the expected behaviour

**Comment by randomorder** [comment]
sorry, please remember to push the configuration update for least connection

**Comment by randomorder** [comment]
![image](https://user-images.githubusercontent.com/5264230/69430944-f5b69480-0d36-11ea-9290-d38ec24062ea.png)
