### ISSUE TITLE
Draft Ansible basic Ansible roles and tasks

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/C106-2017#3]
Let's start with the basics
A webserver role for the GeoServer machines to
- [x] Install OpenJDK 8
- [x] Install Apache Tomcat 8
- [x] Install a vanilla GeoServer WAR into Tomcat (http://geoserver.org/release/stable/)
- [x] Install required utilities to mount an SMB share

A loadbalancer role for the HAProxy machines to
- [x] Install HAProxy

**Comment by randomorder** [comment]
We are going to use GeoServer 2.16.x until 2.16.1 is released

**Comment by giacomoc92** [comment]
Current progress: tasks for openjdk, tomcat, geoserver and haproxy are done.

What's left is smb utilities, some refinements for the platbook and testing.
